First implementation of smime calls
broadinstitute/python-cert_manager pull request #39
Opened 2021-07-28 09:45 UTC by joachimBurket

- Implemented: list, list_by_email, enroll, collect, replace, revoke, revoke_by_email
- Modified the version_hack() function in the helpers in order to use it

2021-07-28 10:02 UTC, joachimBurket commented
I am using your library to manage SMIME certificates on Sectigo. I have started to code the SMIME API calls, and use it for a first dev version.

I had to do some modifications on the version_hack() function in the helpers in order to use it.

I also think some updates on the `Certificate` base class might be needed in order to reuse code.

Finally, I wasn't sure about how the Exceptions are handled. The Sectigo API is returning the detail of the error into the body in the form
```json
{"code":-188,"description":"You already have allowed number of valid certificates."}
```
Should the error handling be left to the user of the library, recovering the error detail in the HTTPError exception, or should the error handling be done into the lib, and a custom exception raised depending on the parsed error.

2021-07-28 15:27 UTC, coreone commented
Looks good to me so far, and thanks for that change to `version_hack`.  I think I wrote that for a function that is no longer in the repo when the structure was a bit different.

For exceptions, I was originally just using requests' `raise_for_status` simply to raise exceptions if non 200-level statuses were returned. I haven't had a chance to address it yet, but #28 was kind of getting at the same issue. I would tend to just use the `HTTPError.response.json()` to pull out that information if needed.

2021-07-28 17:34 UTC, coreone commented
If possible, adding unit tests for this new code would be much appreciated.

2021-07-28 20:06 UTC, joachimBurket commented
Okay thanks for the info for the Exceptions. I'll keep it how it is.

For the tests I wanted to wait for your feedback before starting them. I'll make an update those next days.

2021-08-02 05:28 UTC, joachimBurket commented
I've added the unit tests for the SMIME code. Tell me if something is missing

2021-08-02 13:41 UTC, coreone commented
This looks good, with a few bugs commented inline.  Also, there are a bunch of lint/code style errors that appear, which you can see at:

https://github.com/broadinstitute/python-cert_manager/pull/39/checks?check_run_id=3221026125

2021-08-02 13:48 UTC, joachimBurket commented
I ran pylama in local, I think the linting errors are good now. I had to disable R0914 (Too many local variables) because of the enroll() method (had 22 instead of 15 local vars). Are you okay with that or does it need a refactor ?

2021-08-02 13:59 UTC, coreone commented
Looks like there are still a bunch that are mostly whitespace-related under the `tests` directory.  Only other lint error seems to be in `test_smime.py` on line 143, but you should just be able to add `# pylint: disable=too-many-instance-attributes` right above `class TestEnroll(TestSMIME):` to ignore it.

2021-08-02 14:10 UTC, joachimBurket commented
Sorry I forgot to run pylama on the test folder.. Hope its fine now ;)

2021-08-02 14:28 UTC, coreone requested changes
@joachimBurket Looks like the linting is clear now, but there are still the two places I commented on `Pending` being used instead of `Revoked`.

2021-08-02 14:29 UTC, coreone commented
Additionally, there have been some minor merges, so if you could rebase as well.

2021-08-02 14:40 UTC, joachimBurket commented on tests/test_smime.py
> +        self.assertRaises(Pending, smime.collect, self.test_id)
Ouch didn't see that :O yes it should, I update it

2021-08-02 14:46 UTC, coreone approved these changes

2021-08-02 14:46 UTC, coreone commented
Looks good.  Merging in.  Thanks for the contribution!!

2021-08-02 14:47 UTC, merged

2021-08-02 14:48 UTC, joachimBurket commented
You're welcome! :)